
So basically:
#+begin_quote
 What buddha has said is:
     "chethanawa karmayata mula"
#+end_quote

Chethannawa means something like "intention" in plain english.
 so it's not just a thought.

So it's a bit more involved, or has emotional effect than just a mere thought.

** Remember the affirmation shit I told:

- You have to thank (meaning relase positive vibes (sort of)) to the world.
- they have to be genuin, so not just thought.
- this is the essensne of mithree bhawanawa, it's not just repeating some sentences in your head.

** LoA says:
- you become what you think about
- you beomce what you feel
- thoughts becomem your reality
- you become what you think you are
- whether you believe you can or can't you are always right
- if you say this stuff doesn't work, you are right that stuff doesn't work for you
- if you say this stuff works, you are still right, taht stuff works for you
- you can apply anything to "stuff" here, it could be anything: LoA, Buddhisum, Wasthu, Horescope, Rahu kaale, Maths, Programming, Web development, Going Abroadd.


** Going back to Buddhism:
- Karmaya is what chethanawa builds
- but what you experience is wipakaya
- karmaya applies through wipaakaya

- wipakaya could be come to any of the 5 senses
- so things you feel, touch, taste, hear are wipaka thus some result of karma.
- confusing part is thoughts can also be wipaka (wipaka sith), but thoughts can be not wipaka too (so that's why we are not doomed, we can still escape this karma -> wipaka cycle)

** Karmaya and Wipakaya closer look:

- Wipaka you get is a result of past karma.
- past here is any moment prior to this moment.
- so what your "chethana" a minute a go can becomem a karma wipaka in any moment from now on wards.

** How LoA is Karma

- You "chethana" you had in the so called "past" gives you "wipaka"
- you become what you feel
- so what your "chethana" at this moment affects what is to come to you in the future.
- I can go on and write more, but I think if you read this long you get the point.
